export interface Formula {
  id: string;
  name: string;
  formula: string;
  latex: string;
  explanation: string;
  when: string;
  chapter?: number;
}

export interface Section {
  id: string;
  title: string;
  formulas: Formula[];
}

export const SECTIONS: Section[] = [
  {
    id: "descriptive",
    title: "Descriptive Statistics",
    formulas: [
      {
        id: "mean",
        name: "Sample Mean",
        formula: "Ȳ = ΣYᵢ / n",
        latex: "\\bar{Y} = \\dfrac{\\sum Y_i}{n}",
        explanation: "The arithmetic average — add all observations and divide by the count. Best estimate of the population mean μ.",
        when: "Always the starting point. Pair with the standard error to quantify precision.",
        chapter: 3,
      },
      {
        id: "sd-conceptual",
        name: "Standard Deviation (conceptual)",
        formula: "s = √[ Σ(Yᵢ − Ȳ)² / (n−1) ]",
        latex: "s = \\sqrt{\\dfrac{\\sum(Y_i - \\bar{Y})^2}{n-1}}",
        explanation: "How spread out data are around the mean. Dividing by n−1 corrects for bias (Bessel's correction).",
        when: "Quantifying variability. Used in t-tests, CIs, and ANOVA.",
        chapter: 3,
      },
      {
        id: "sd-computational",
        name: "Standard Deviation (computational)",
        formula: "s = √[ (ΣYᵢ² − nȲ²) / (n−1) ]",
        latex: "s = \\sqrt{\\dfrac{\\sum Y_i^2 - n\\bar{Y}^2}{n-1}}",
        explanation: "Algebraically equivalent but avoids rounding errors when computing by hand. ΣYᵢ² = square each value then sum.",
        when: "Preferred for hand calculations from raw data.",
        chapter: 3,
      },
      {
        id: "se",
        name: "Standard Error of the Mean",
        formula: "SE_Ȳ = s / √n",
        latex: "SE_{\\bar{Y}} = \\dfrac{s}{\\sqrt{n}}",
        explanation: "How much Ȳ varies from sample to sample. Larger n → smaller SE. Doubling precision requires quadrupling n.",
        when: "Building confidence intervals for μ, or as the t-test denominator.",
        chapter: 4,
      },
    ],
  },
  {
    id: "probability",
    title: "Probability Distributions",
    formulas: [
      {
        id: "binomial",
        name: "Binomial Distribution",
        formula: "Pr[X=x] = C(n,x) · pˣ · (1−p)ⁿ⁻ˣ",
        latex: "\\Pr[X=x] = \\binom{n}{x}\\, p^{\\,x}\\,(1-p)^{n-x}",
        explanation: "Probability of exactly x successes in n independent trials, each with probability p. Mean = np, Variance = np(1−p).",
        when: "Counting successes in a fixed number of binary trials. E.g. # of mutant offspring.",
        chapter: 7,
      },
      {
        id: "poisson",
        name: "Poisson Distribution",
        formula: "P[X=x] = μˣ · e^(−μ) / x!",
        latex: "P[X=x] = \\dfrac{\\mu^x \\cdot e^{-\\mu}}{x!}",
        explanation: "Probability of x events when the average rate is μ. Key property: mean = variance = μ.",
        when: "Counting rare, random events per unit time or space. Test fit with χ² GOF.",
        chapter: 8,
      },
      {
        id: "normal",
        name: "Normal Distribution",
        formula: "f[x] = (1/√(2πσ²)) · e^(−(x−μ)²/(2σ²))",
        latex: "f(x) = \\dfrac{1}{\\sqrt{2\\pi\\sigma^2}} \\cdot e^{-\\dfrac{(x-\\mu)^2}{2\\sigma^2}}",
        explanation: "The bell curve, described by mean μ and variance σ². 68% within 1σ, 95% within 2σ, 99.7% within 3σ.",
        when: "Describing symmetric continuous measurements. Many parametric tests assume normally distributed errors/residuals, or normality within groups, especially for small samples.",
        chapter: 10,
      },
      {
        id: "bayes",
        name: "Bayes' Theorem",
        formula: "Pr[A|B] = Pr[B|A] · Pr[A] / Pr[B]",
        latex: "\\Pr[A|B] = \\dfrac{\\Pr[B|A]\\cdot\\Pr[A]}{\\Pr[B]}",
        explanation: "Updates probability of A given evidence B. Pr[A] = prior, Pr[B|A] = likelihood, Pr[A|B] = posterior.",
        when: "Reversing conditional probabilities. E.g. given a positive test, actual probability of disease?",
        chapter: 5,
      },
    ],
  },
  {
    id: "ci",
    title: "Confidence Intervals",
    formulas: [
      {
        id: "ci-mean",
        name: "CI for the Mean",
        formula: "Ȳ ± SE_Ȳ · t_{α(2), df}",
        latex: "\\bar{Y} \\pm SE_{\\bar{Y}} \\cdot t_{\\alpha(2),\\, df}",
        explanation: "95% CI (α = 0.05): if repeated, 95% of intervals would contain true μ. df = n−1.",
        when: "After estimating a mean. Report as: Ȳ = X (95% CI: lower, upper).",
        chapter: 4,
      },
      {
        id: "ci-diff-means",
        name: "CI for Difference in Means",
        formula: "(Ȳ₁ − Ȳ₂) ± SE_{Ȳ₁−Ȳ₂} · t_{α(2), df}",
        latex: "(\\bar{Y}_1 - \\bar{Y}_2) \\pm SE_{\\bar{Y}_1-\\bar{Y}_2} \\cdot t_{\\alpha(2),\\, df}",
        explanation: "Interval for the true difference μ₁ − μ₂. If it excludes 0, the difference is significant at level α.",
        when: "After a two-sample t-test to report the plausible range of the difference.",
        chapter: 12,
      },
      {
        id: "agresti-coull",
        name: "Agresti-Coull (Proportion CI)",
        formula: "p̃ = (X+2)/(n+4)   then   p̃ ± 1.96·√(p̃(1−p̃)/(n+4))",
        latex: "\\tilde{p} = \\dfrac{X+2}{n+4}, \\quad \\tilde{p} \\pm 1.96\\sqrt{\\dfrac{\\tilde{p}(1-\\tilde{p})}{n+4}}",
        explanation: "Better than the Wald interval. Adding 2 phantom successes and 2 failures stabilizes the interval near 0 or 1.",
        when: "Estimating a population proportion p. Always preferred over Wald CI in BIOL 300.",
        chapter: 7,
      },
      {
        id: "ci-variance",
        name: "CI for the Variance",
        formula: "df·s²/χ²_{α/2, df}  ≤  σ²  ≤  df·s²/χ²_{1−α/2, df}",
        latex: "\\dfrac{df \\cdot s^2}{\\chi^2_{\\alpha/2,\\, df}} \\leq \\sigma^2 \\leq \\dfrac{df \\cdot s^2}{\\chi^2_{1-\\alpha/2,\\, df}}",
        explanation: "Uses two χ² critical values (asymmetric interval because χ² is skewed). df = n−1.",
        when: "Estimating population variance σ² directly from a single sample.",
        chapter: 11,
      },
    ],
  },
  {
    id: "chi2",
    title: "Chi-Square & Proportions",
    formulas: [
      {
        id: "chi-stat",
        name: "Chi-Square Statistic",
        formula: "χ² = Σ (Observed_i − Expected_i)² / Expected_i",
        latex: "\\chi^2 = \\sum \\dfrac{(O_i - E_i)^2}{E_i}",
        explanation: "Larger χ² = more departure from H₀. df = (categories − 1) minus parameters estimated. Assumptions: expected count > 1 in all cells; no more than 20% of cells have expected count < 5.",
        when: "Testing fit to a theoretical distribution (GOF) or independence in a contingency table.",
        chapter: 8,
      },
      {
        id: "odds-ratio",
        name: "Odds Ratio",
        formula: "ÔR = (a · d) / (b · c)",
        latex: "\\widehat{OR} = \\dfrac{a \\cdot d}{b \\cdot c}",
        explanation: "From a 2×2 table (a=top-left, b=top-right, c=bottom-left, d=bottom-right). OR > 1: event more likely in group 1.",
        when: "Measuring association between two binary variables in a 2×2 contingency table.",
        chapter: 9,
      },
      {
        id: "odds-ratio-ci",
        name: "CI for Odds Ratio",
        formula: "ln(ÔR) ± Z_α · SE[ln(ÔR)]   →   back-transform with e^(·)",
        latex: "\\ln(\\widehat{OR}) \\pm Z_\\alpha \\cdot SE[\\ln(\\widehat{OR})]",
        explanation: "The CI is built on the log scale (where ln(OR) is approximately normal), then exponentiated. If CI excludes 1, association is significant.",
        when: "Reporting uncertainty around an estimated odds ratio. If CI includes 1, no significant association.",
        chapter: 9,
      },
    ],
  },
  {
    id: "ttests",
    title: "t-Tests",
    formulas: [
      {
        id: "one-sample-t",
        name: "One-Sample t",
        formula: "t = (Ȳ − μ₀) / (s / √n)",
        latex: "t = \\dfrac{\\bar{Y} - \\mu_0}{s / \\sqrt{n}}",
        explanation: "Tests H₀: μ = μ₀. Large |t| means Ȳ is far from μ₀ in SE units. df = n−1.",
        when: "Comparing a sample mean to a specific hypothesized value. One group, one mean.",
        chapter: 11,
      },
      {
        id: "pooled-sp2",
        name: "Pooled Sample Variance",
        formula: "sp² = (df₁·s₁² + df₂·s₂²) / (df₁ + df₂)",
        latex: "s_p^2 = \\dfrac{df_1 s_1^2 + df_2 s_2^2}{df_1 + df_2}",
        explanation: "Weighted average of both groups' variances. Valid only when assuming σ₁² = σ₂².",
        when: "First step in the pooled two-sample t-test.",
        chapter: 12,
      },
      {
        id: "se-pooled",
        name: "SE for Pooled Two-Sample t",
        formula: "SE_{Ȳ₁−Ȳ₂} = √[ sp² · (1/n₁ + 1/n₂) ]",
        latex: "SE_{\\bar{Y}_1-\\bar{Y}_2} = \\sqrt{s_p^2\\!\\left(\\dfrac{1}{n_1} + \\dfrac{1}{n_2}\\right)}",
        explanation: "Standard error of the difference in means, assuming equal variances.",
        when: "Part of pooled two-sample t-test, after computing sp².",
        chapter: 12,
      },
      {
        id: "two-sample-t",
        name: "Two-Sample t (Pooled)",
        formula: "t = (Ȳ₁ − Ȳ₂) / SE_{Ȳ₁−Ȳ₂}",
        latex: "t = \\dfrac{\\bar{Y}_1 - \\bar{Y}_2}{SE_{\\bar{Y}_1-\\bar{Y}_2}}",
        explanation: "Tests H₀: μ₁ = μ₂ assuming equal variances. df = n₁ + n₂ − 2.",
        when: "Comparing two independent group means when σ₁² = σ₂² is plausible.",
        chapter: 12,
      },
      {
        id: "welch-t",
        name: "Welch's Two-Sample t",
        formula: "t = (Ȳ₁ − Ȳ₂) / √(s₁²/n₁ + s₂²/n₂)",
        latex: "t = \\dfrac{\\bar{Y}_1 - \\bar{Y}_2}{\\sqrt{s_1^2/n_1 + s_2^2/n_2}}",
        explanation: "Does NOT assume equal variances. More robust than pooled version. Uses Welch-Satterthwaite df.",
        when: "Default choice for two independent means — use unless told variances are equal.",
        chapter: 12,
      },
      {
        id: "welch-df",
        name: "Welch-Satterthwaite df",
        formula: "df = (s₁²/n₁ + s₂²/n₂)²  /  [ (s₁²/n₁)²/(n₁−1) + (s₂²/n₂)²/(n₂−1) ]",
        latex: "df = \\dfrac{(s_1^2/n_1 + s_2^2/n_2)^2}{\\dfrac{(s_1^2/n_1)^2}{n_1-1} + \\dfrac{(s_2^2/n_2)^2}{n_2-1}}",
        explanation: "Approximate df for Welch's t-test. Always round down. Will be between min(n₁,n₂)−1 and n₁+n₂−2.",
        when: "Needed to look up the critical t-value in Welch's t-test.",
        chapter: 12,
      },
      {
        id: "variance-ratio-f",
        name: "Variance Ratio F-Test",
        formula: "F = s₁² / s₂²",
        latex: "F = \\dfrac{s_1^2}{s_2^2}",
        explanation: "Tests H₀: σ₁² = σ₂² (equal variances). Place the larger variance in the numerator. df₁ = n₁−1, df₂ = n₂−1.",
        when: "A test for the null hypothesis that two normal populations have the same variance. Do NOT use it to decide whether to use Welch's t-test.",
        chapter: 12,
      },
    ],
  },
  {
    id: "regression",
    title: "Regression & Correlation",
    formulas: [
      {
        id: "sp-xy",
        name: "Sum of Cross-Products",
        formula: "SP_xy = Σ(Xᵢ−X̄)(Yᵢ−Ȳ)  =  ΣXY − (ΣX)(ΣY)/n",
        latex: "SP_{xy} = \\sum(X_i-\\bar{X})(Y_i-\\bar{Y}) = \\sum XY - \\dfrac{(\\sum X)(\\sum Y)}{n}",
        explanation: "Measures how X and Y covary. Computational form avoids rounding error.",
        when: "First step in regression and correlation. Compute alongside SS_x.",
        chapter: 16,
      },
      {
        id: "ss-x",
        name: "Sum of Squares for X",
        formula: "SS_x = Σ(Xᵢ−X̄)²  =  ΣX² − (ΣX)²/n",
        latex: "SS_x = \\sum(X_i-\\bar{X})^2 = \\sum X^2 - \\dfrac{(\\sum X)^2}{n}",
        explanation: "Total variability in predictor X. Note: (ΣX)²/n is the correction factor.",
        when: "Required for slope b, correlation r, and SE_b.",
        chapter: 16,
      },
      {
        id: "ss-total",
        name: "SS Total (for Y)",
        formula: "SS_Total = ΣYᵢ² − (ΣYᵢ)²/n",
        latex: "SS_{Total} = \\sum Y_i^2 - \\dfrac{(\\sum Y_i)^2}{n}",
        explanation: "Total variability in the response variable Y. Used to partition variance into regression and residual.",
        when: "Computing r² and MS_residual in regression.",
        chapter: 17,
      },
      {
        id: "ss-regression",
        name: "SS Regression",
        formula: "SS_regression = b · SP_xy",
        latex: "SS_{reg} = b \\cdot SP_{xy}",
        explanation: "Variability in Y explained by the linear relationship with X.",
        when: "Computing r² = SS_regression / SS_total.",
        chapter: 17,
      },
      {
        id: "ss-residual",
        name: "SS Residual",
        formula: "SS_residual = SS_Total − SS_regression",
        latex: "SS_{res} = SS_{Total} - SS_{reg}",
        explanation: "Variability in Y NOT explained by X. Used to compute MS_residual.",
        when: "Computing MS_residual = SS_residual / (n−2).",
        chapter: 17,
      },
      {
        id: "slope",
        name: "Regression Slope",
        formula: "b = SP_xy / SS_x",
        latex: "b = \\dfrac{SP_{xy}}{SS_x}",
        explanation: "Change in predicted Y per 1-unit increase in X. Sign = direction, magnitude = rate. df = n−2.",
        when: "The key parameter in linear regression.",
        chapter: 17,
      },
      {
        id: "intercept",
        name: "Regression Intercept",
        formula: "a = Ȳ − b·X̄",
        latex: "a = \\bar{Y} - b\\bar{X}",
        explanation: "Predicted Y when X = 0. Often meaningless if X = 0 is outside the data range. Fitted line: Ŷ = a + bX.",
        when: "After computing b. Needed to make predictions.",
        chapter: 17,
      },
      {
        id: "ms-residual",
        name: "Residual Mean Square",
        formula: "MS_residual = SS_residual / (n−2)",
        latex: "MS_{res} = \\dfrac{SS_{res}}{n-2}",
        explanation: "Average squared deviation from the fitted line. Smaller = better fit. df = n−2.",
        when: "Computing SE_b and assessing model fit.",
        chapter: 17,
      },
      {
        id: "se-b",
        name: "Standard Error of Slope",
        formula: "SE_b = √( MS_residual / SS_x )",
        latex: "SE_b = \\sqrt{\\dfrac{MS_{res}}{SS_x}}",
        explanation: "Precision of the estimated slope b.",
        when: "Testing H₀: β = 0, or building a CI for the true slope.",
        chapter: 17,
      },
      {
        id: "ci-slope",
        name: "CI for Slope",
        formula: "b ± t_{α[2], df} · SE_b",
        latex: "b \\pm t_{\\alpha[2],\\, df} \\cdot SE_b",
        explanation: "Confidence interval for the true slope β. df = n−2. If CI excludes 0, slope is significant.",
        when: "Reporting uncertainty in a regression slope estimate.",
        chapter: 17,
      },
      {
        id: "t-slope",
        name: "t-Test for Slope",
        formula: "t = (b − β₀) / SE_b",
        latex: "t = \\dfrac{b - \\beta_0}{SE_b}",
        explanation: "Tests H₀: β = β₀ (usually β₀ = 0, i.e. no linear relationship). df = n−2.",
        when: "Testing whether the linear slope differs from a null hypothesized value (often 0).",
        chapter: 17,
      },
      {
        id: "ci-prediction",
        name: "CI for Predicted Value",
        formula: "Ŷ ± t_{α[2], df} · SE_Ŷ",
        latex: "\\hat{Y} \\pm t_{\\alpha[2],\\, df} \\cdot SE_{\\hat{Y}}",
        explanation: "Confidence interval for the mean response at a given X. SE_Ŷ accounts for uncertainty in both a and b.",
        when: "Estimating the mean Y at a specific X value.",
        chapter: 17,
      },
      {
        id: "r-squared",
        name: "Coefficient of Determination (r²)",
        formula: "r² = SS_regression / SS_Total",
        latex: "r^2 = \\dfrac{SS_{reg}}{SS_{Total}}",
        explanation: "Proportion of variance in Y explained by X. r² = 0.80 means 80% of variability is accounted for.",
        when: "Reporting goodness of fit. Ranges 0 to 1.",
        chapter: 17,
      },
      {
        id: "pearson-r",
        name: "Pearson Correlation",
        formula: "r = SP_xy / √(SS_x · SS_y)",
        latex: "r = \\dfrac{SP_{xy}}{\\sqrt{SS_x \\cdot SS_y}}",
        explanation: "Standardized linear association. Ranges −1 to +1. Measures only linear relationships.",
        when: "Measuring strength/direction of linear association between two continuous variables.",
        chapter: 16,
      },
      {
        id: "se-r",
        name: "Standard Error of r",
        formula: "SE_r = √[ (1 − r²) / (n−2) ]",
        latex: "SE_r = \\sqrt{\\dfrac{1 - r^2}{n-2}}",
        explanation: "Use for testing H₀: ρ = 0 via t = r / SE_r, df = n−2. Not for CIs — use Fisher's z instead.",
        when: "Hypothesis testing for correlation only.",
        chapter: 16,
      },
      {
        id: "fisher-z",
        name: "Fisher's z-Transform",
        formula: "z = 0.5·ln[(1+r)/(1−r)]   and   σ_z = √(1/(n−3))",
        latex: "z = \\tfrac{1}{2}\\ln\\!\\dfrac{1+r}{1-r}, \\quad \\sigma_z = \\dfrac{1}{\\sqrt{n-3}}",
        explanation: "Transforms r to approximately normal z. Build CI on z-scale, back-transform: r = (e²ᶻ−1)/(e²ᶻ+1).",
        when: "Building confidence intervals for the Pearson correlation r.",
        chapter: 16,
      },
      {
        id: "spearman",
        name: "Spearman Rank Correlation",
        formula: "rₛ = 1 − 6Σdᵢ² / (n³ − n)",
        latex: "r_s = 1 - \\dfrac{6\\sum d_i^2}{n^3 - n}",
        explanation: "Non-parametric correlation using ranks. dᵢ = rank(Xᵢ) − rank(Yᵢ). Measures monotonic association.",
        when: "Data violate normality or are ordinal. Identify-only in BIOL 300.",
        chapter: 13,
      },
      {
        id: "pooled-ms-error",
        name: "Pooled MS_error (Comparing Regressions)",
        formula: "(MS_error)_p = [(SS_error)₁ + (SS_error)₂] / [(df_error)₁ + (df_error)₂]",
        latex: "(MS_e)_p = \\dfrac{(SS_e)_1 + (SS_e)_2}{(df_e)_1 + (df_e)_2}",
        explanation: "Combines residual variance from two separate regressions, assuming they share the same σ². Used when comparing slopes.",
        when: "Testing whether two regression lines have the same slope (H₀: β₁ = β₂).",
        chapter: 17,
      },
      {
        id: "se-b1-b2",
        name: "SE for Difference in Slopes",
        formula: "SE_{b₁−b₂} = √[ (MS_error)_p/SS_x₁ + (MS_error)_p/SS_x₂ ]",
        latex: "SE_{b_1-b_2} = \\sqrt{\\dfrac{(MS_e)_p}{SS_{x_1}} + \\dfrac{(MS_e)_p}{SS_{x_2}}}",
        explanation: "Standard error of the difference between two regression slopes. Uses pooled residual MS.",
        when: "Building a t-test or CI for the difference between two slopes: t = (b₁−b₂) / SE_{b₁−b₂}.",
        chapter: 17,
      },
    ],
  },
  {
    id: "anova",
    title: "ANOVA",
    formulas: [
      {
        id: "grand-mean",
        name: "Grand Mean",
        formula: "Ȳ = Σ nᵢȲᵢ / N",
        latex: "\\bar{Y} = \\dfrac{\\sum n_i \\bar{Y}_i}{N}",
        explanation: "Overall mean weighted by group size. N = total sample size.",
        when: "Computing MS_groups and R² in ANOVA.",
        chapter: 15,
      },
      {
        id: "ms-groups",
        name: "MS Between Groups",
        formula: "MS_groups = Σ nᵢ(Ȳᵢ − Ȳ)² / (k−1)",
        latex: "MS_{groups} = \\dfrac{\\sum n_i(\\bar{Y}_i - \\bar{Y})^2}{k-1}",
        explanation: "Between-group variability weighted by n. k = number of groups, df = k−1. Large = groups spread far apart.",
        when: "Numerator of F. Reflects signal.",
        chapter: 15,
      },
      {
        id: "ms-error",
        name: "MS Within Groups (Error)",
        formula: "MS_error = Σ sᵢ²(nᵢ−1) / (N−k)",
        latex: "MS_{error} = \\dfrac{\\sum s_i^2(n_i-1)}{N-k}",
        explanation: "Pooled within-group variance. Also called MS_within or s²_pooled. df = N−k. Assumes equal variances.",
        when: "Denominator of F and Tukey-Kramer SE. Reflects noise.",
        chapter: 15,
      },
      {
        id: "f-stat",
        name: "F-Statistic",
        formula: "F = MS_groups / MS_error",
        latex: "F = \\dfrac{MS_{groups}}{MS_{error}}",
        explanation: "Signal-to-noise ratio. Under H₀, F ≈ 1. df₁ = k−1, df₂ = N−k.",
        when: "Testing H₀: all group means equal. Use for 3+ groups.",
        chapter: 15,
      },
      {
        id: "anova-r2",
        name: "ANOVA R²",
        formula: "R² = SS_groups / SS_total",
        latex: "R^2 = \\dfrac{SS_{groups}}{SS_{total}}",
        explanation: "Proportion of variance explained by group membership (η²). Effect size measure.",
        when: "After significant F-test. Report as effect size.",
        chapter: 15,
      },
      {
        id: "tukey-q",
        name: "Tukey-Kramer q",
        formula: "q = (Ȳᵢ − Ȳⱼ) / SE   where   SE = √[ s²_pooled · (1/nᵢ + 1/nⱼ) ]",
        latex: "q = \\dfrac{\\bar{Y}_i - \\bar{Y}_j}{SE}, \\quad SE = \\sqrt{s^2_{pooled}\\!\\left(\\dfrac{1}{n_i}+\\dfrac{1}{n_j}\\right)}",
        explanation: "Post-hoc pairwise comparison controlling family-wise error. s²_pooled = MS_error. Compare to Table F critical value.",
        when: "After significant ANOVA, to find which specific pairs differ.",
        chapter: 15,
      },
    ],
  },
];
